### ISSUE TITLE
v2.0 translation

### ISSUE THREAD

**Issue by gbezyuk** [vuejs-ru/old.ru.vuejs.org#21]
Hi guys. I've started to work on Russian translation for 2.0 documentation at https://github.com/gbezyuk/ru.vuejs.org
If you work on the same issue, let's sync our efforts.

**Comment by iJackUA** [comment]
@gbezyuk  sorry for a long response time.
Unfortunately, this project got out of the main priority scope for me. And it looks like no other members activity on 2.0 docs translation. So literally there are no efforts here to sync with.

I propose to add you as an Admin for this organization `vuejs-ru`, so you can manage it, add your translation fork (and maybe translations for other Vue repos like router etc.) and moderate https://github.com/vuejs-ru/Discussion (that is rather popular russian-speaking Gitter chanell).

**Comment by iJackUA** [comment]
I have remembered about this thanks to flame in comments here https://vk.com/wall-30666517_1434369
ha-ha :)

**Comment by gbezyuk** [comment]
Finally! =) Sure, add me! Thanx!

**Comment by iJackUA** [comment]
Done

**Comment by ghost** [comment]
Grac!
