### ISSUE TITLE
Translation plan and progress tracking

### ISSUE THREAD

**Issue by iJackUA** [vuejs-ru/old.ru.vuejs.org#4]
# Warning

Due to 1.0 release coming in end of October / early November and completely rewritten docs http://rc.vuejs.org/. Please stop current **v0.12** docs translation. New translation plan should be done.
### How to help with translation
- Select a page with :grey_question: not assigned status
- Write a comment in this issue like `I am taking page-name.md`
- Create fork of this repo
- Be sure that you are making a translation based on `lang-ru` branch
- Create a pull request to this repo with name `[WIP] page-name.md` even if/while translation is not completed yet  (for everyone to know that you are really working on it, or if you will leave it - someone could use your starting point and continue, so your work would not  be lost in any case)
- When you finish a translation rename a pull  request and repo `[WIP]` prefix
- Be sure that your branch is up-to-date with latest state of this repo's `lang-ru` and pull request could be merged without conflicts
- Make a comment here like `Finished page-name.md <link to pull request>`
- Someone will review your translation and I'll accept a pull request
### Review

**Even if you are not very good in English to translate by yourself, or have no time etc. You still can contribute.**  
If you see a :see_no_evil: `review needed` label on page. It means that translation is completed, but some native speaker should review it in Russian. To track down bad wording, mistypes or anything that "looks weird" for a Russian native-speaker. If you found something - ideally make s fix pull request, or at least create an issue with back links to "error" lines.
If you have reviewed some doc and it looks fine for you - write here in comments to mark it as `done`  :+1: 
### Priorities

Pages are ordered in the table as they are ordered in docs, so it is supposed to translate them in the same order. You are free to select any page, but it's better to go one-by-one in the list
### "ON HOLD" Notice

Pages marked as "**on hold**" should not be translated till Vue 1.0.0 officially released. As recent changes (in 1.0.0-alpha) to attributes binding notation will change a lot and these doc pages could get a lot of updates and changes. It is almost have no sense to spend a time on them right now.
### /source/guide

| Page | Translator | Reviewer | Status |
| --- | --- | --- | --- |
| installation.md | @OEvgeny | @iJackUA | :+1: done |
| index.md | @OEvgeny | @iJackUA | :+1: done |
| directives.md | @OEvgeny | @iJackUA | :+1: done |
| filters.md | @OEvgeny | @iJackUA | :+1: done |
| list.md | @OEvgeny | @iJackUA | :+1: done |
| events.md | @OEvgeny | @iJackUA | :+1: done |
| forms.md | @OEvgeny | @iJackUA | :+1: done |
| computed.md | @iJackUA |  | :see_no_evil: review needed |
| custom-directive.md | @iJackUA |  | :see_no_evil: review needed |
| custom-filter.md | @iJackUA |  | :see_no_evil: review needed |
| components.md | _on hold_ |  | :grey_question: not assigned |
| transitions.md | @simplesmiler | @iJackUA | :+1: done |
| application.md | @iJackUA |  | :construction: work in progress |
| extending.md | @iJackUA |  | :see_no_evil: review needed |
| best-practices.md | _on hold_ |  | :grey_question: not assigned |
| faq.md |  |  | :grey_question: not assigned |
### /source/api

| Page | Translator | Reviewer | Status |
| --- | --- | --- | --- |
| index.md | @iJackUA |  | :see_no_evil: review needed |
| options.md |  |  | :grey_question: not assigned |
| instance-properties.md |  |  | :grey_question: not assigned |
| instance-methods.md |  |  | :grey_question: not assigned |
| global-api.md |  |  | :grey_question: not assigned |
| directives.md | _on hold_ |  | :grey_question: not assigned |
| filters.md |  |  | :grey_question: not assigned |
| elements.md |  |  | :grey_question: not assigned |
### /source/examples

| Page | Translator | Reviewer | Status |
| --- | --- | --- | --- |
| all pages description | @OEvgeny | @iJackUA | :+1: done |
### /themes/vue/layout/*.ejs

| Page | Translator | Reviewer | Status |
| --- | --- | --- | --- |
| all pages description | @iJackUA | @iJackUA | :+1: done |
### Setup gh-pages site http://vuejs-ru.github.io/vuejs.org/

@iJackUA  :+1: done 
### Legend

| Status | Emoji |
| --- | --- |
| done | :+1: |
| in review | :eyes: |
| review needed | :see_no_evil: |
| work in progress | :construction: |
| not assigned | :grey_question: |

**Comment by yyx990803** [comment]
:+1:

**Comment by aXenom** [comment]
Priorities?

**Comment by iJackUA** [comment]
@aXenom I think Guide should be first, then Api.
As for pages order - it doesn't play any role as for me.

**Comment by simplesmiler** [comment]
Taken `transitions.md`: https://github.com/vuejs-ru/vuejs.org/pull/10

**Comment by Nayfania** [comment]
Taken faq.md

**Comment by iJackUA** [comment]
Ok. Nice work, but due to Vue 1.0 release - starting all over :)
[Translation plan and progress tracking (version 1.0)](https://github.com/vuejs-ru/vuejs.org/issues/16)
New translation list made. Let's try to "give the second life" to some translated parts of documentation, but in general consider 1.0 docs translation as "from he very beginning" (due to big structural and content changes)
